### ISSUE TITLE
unresolved external symbol

### ISSUE THREAD

**Issue by albanm** [gagern/libxmljs#5] opened 2016-01-05 20:32 UTC
Hello,

I use libxmljs-mt in a [node-libxml-xsd](https://github.com/albanm/node-libxml-xsd) module as well as node-libxslt. Build on windows the build fails with "unresolved external symbol" errors, cf [appveyor](https://ci.appveyor.com/project/albanm/node-libxml-xsd/build/1.0.10).

Any idea would be greatly appreciated !

**Comment by gagern** [comment] 2016-01-06 01:18
As far as I can see, the problem is because you import [`<xml_syntax_error.h>`](https://github.com/gagern/libxmljs/blob/master/src/xml_syntax_error.h) which is not designed for external use and which does not mark its symbols for DLL exporting. Are you certain that validation errors get reported via the libxml structured error reporting facilities? If so, then the approach you chose makes sense and I probably should mark these classes with `LIBXMLJS_API`. Can you try that locally?

**Comment by albanm** [comment] 2016-01-06 14:44
I have no windows system, but I managed to build my clone of libxmljs-mt from source in appveyor, everything works fine: https://ci.appveyor.com/project/albanm/node-libxml-xsd

 The fix commit is [here](https://github.com/albanm/libxmljs/commit/29e115d88e6561ced77c5ba5122d3b7522c628fe). It doesn't really deserve a PR and I don't feel able to write the appropriate comment. Could you do this and release a version ?

Thanks !

**Comment by gagern** [comment] 2016-01-06 17:02
I didn't feel like writing much of a comment either. The summary line already captures the core of what this is about, so I merged your commit unmodified, and [released libxmljs-mt 0.16.0](https://github.com/gagern/libxmljs/releases/tag/v0.16.0-mt).

**Closed as completed by gagern** 2016-01-06 17:02 UTC

**Comment by albanm** [comment] 2016-01-06 20:48
thanks !
